config/routes.rb
Rails.application.routes.draw do

  
  root 'pages#home'
  get 'about', to: 'pages#about'
  
  resources :articles
  
  get "signup", to: 'users#new'
  resources :users,  except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  resources :categories, except: [:destroy]
  
  

end

app/views/articles.1/edit.html.erb
<h1> Editing an existing article </h1>

<!-- block for display validation messages -->
<% if @article.errors.any? %>
<h2>The following errors prevented the article from getting saved... please re-enter.</h2>
<ul>
  <% @article.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
</ul>

<% end %>

<!-- use rails  form for helpers-->
<%= form_for @article do |f| %>

<p>
  <%= f.label :title %><br>
  <%= f.text_field :title %>
</p>

<p>
  <%= f.label :description %><br>
  <%= f.text_field :description %>
</p>

<p>
  <%= f.submit %>
</p>

<% end %>

<p>
  <%= link_to "Back to articles listing. ", articles_path %>
</p>

app/views/articles.1/index.html.erb
<h1>Listing all articles</h1>
<p>
  <%= link_to "Create new article", new_article_path %>
</p>

<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
  </tr>
  
  <% @articles.each do |article| %>
  <tr>
    <td><%= article.title %></td>
    <td><%= article.description %></td>
    <td><%= link_to "Edit", edit_article_path(article) %></td>
    <td><%= link_to "Show", article_path(article) %></td>
    
    
    </tr>
    <% end %>
</table>

app/views/articles.1/new.html.erb
<h1> create a new article</h1>

<!-- block for display validation messages -->
<% if @article.errors.any? %>
<h2>The following errors prevented the article from getting created... please re-enter.</h2>
<ul>
  <% @article.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
</ul>

<% end %>

<!-- use rails  form for helpers-->
<%= form_for @article do |f| %>

<p>
  <%= f.label :title %><br>
  <%= f.text_field :title %>
</p>

<p>
  <%= f.label :description %><br>
  <%= f.text_field :description %>
</p>

<p>
  <%= f.submit %>
</p>

<% end %>

<p>
  <%= link_to "Back to articles listing. ", articles_path %>
</p>

app/views/articles.1/show.html.erb
<h1>showing selcted article</h1>

<p>Title <%= @article.title %>
</p>

<p>Description <%= @article.description %>
</p>

<p>
  <%= link_to "Edit", edit_article_path(@article) %>
</p>
<p>
  <%= link_to "Back to articles listing. ", articles_path %>
</p>